/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.nk.views;

/**
 *
 * @author Pc
 */
public class VCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VCliente
     */
    public VCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellPa = new javax.swing.JLabel();
        txtApellPa = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblApellMa = new javax.swing.JLabel();
        txtApellMa = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblTítuloNewCliente = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lblIconoCliente = new javax.swing.JLabel();
        lblTituloListaClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(54, 57, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(88, 101, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombres.setBackground(new java.awt.Color(88, 101, 242));
        txtNombres.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(250, 250, 250));
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 300, 40));

        lblNombres.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("Nombres");
        jPanel2.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 300, 10));

        lblApellPa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblApellPa.setForeground(new java.awt.Color(255, 255, 255));
        lblApellPa.setText("Apellido Paterno");
        jPanel2.add(lblApellPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtApellPa.setBackground(new java.awt.Color(88, 101, 242));
        txtApellPa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtApellPa.setForeground(new java.awt.Color(250, 250, 250));
        txtApellPa.setBorder(null);
        txtApellPa.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtApellPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 300, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 300, 10));

        lblApellMa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblApellMa.setForeground(new java.awt.Color(255, 255, 255));
        lblApellMa.setText("Apellido Materno");
        jPanel2.add(lblApellMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        txtApellMa.setBackground(new java.awt.Color(88, 101, 242));
        txtApellMa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtApellMa.setForeground(new java.awt.Color(250, 250, 250));
        txtApellMa.setBorder(null);
        txtApellMa.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtApellMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 300, 40));

        jSeparator3.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator3.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 300, 10));

        lblDNI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI.setText("DNI");
        jPanel2.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        txtDNI.setBackground(new java.awt.Color(88, 101, 242));
        txtDNI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(250, 250, 250));
        txtDNI.setBorder(null);
        txtDNI.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 300, 40));

        jSeparator4.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator4.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 300, 10));

        lblTelefono.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Teléfono");
        jPanel2.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(88, 101, 242));
        txtTelefono.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(250, 250, 250));
        txtTelefono.setBorder(null);
        txtTelefono.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 300, 40));

        jSeparator5.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator5.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 300, 10));

        lblTítuloNewCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewCliente.setText("NUEVO CLIENTE");
        jPanel2.add(lblTítuloNewCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(54, 57, 63));
        btnEliminar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 130, 50));

        btnRegistrar.setBackground(new java.awt.Color(54, 57, 63));
        btnRegistrar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 130, 50));

        btnConsultar.setBackground(new java.awt.Color(54, 57, 63));
        btnConsultar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setFocusPainted(false);
        btnConsultar.setFocusable(false);
        btnConsultar.setOpaque(true);
        btnConsultar.setRequestFocusEnabled(false);
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 130, 50));

        btnListar.setBackground(new java.awt.Color(54, 57, 63));
        btnListar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.setBorder(null);
        btnListar.setContentAreaFilled(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.setFocusPainted(false);
        btnListar.setFocusable(false);
        btnListar.setOpaque(true);
        btnListar.setRequestFocusEnabled(false);
        btnListar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 130, 50));

        btnActualizar.setBackground(new java.awt.Color(54, 57, 63));
        btnActualizar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setFocusable(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setRequestFocusEnabled(false);
        btnActualizar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 430, 730));

        lblIconoCliente.setBackground(new java.awt.Color(54, 57, 63));
        lblIconoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblIconoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoCliente.setText("(colocar icono cliente - editar luego)");
        jPanel1.add(lblIconoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 180));

        lblTituloListaClientes.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTituloListaClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloListaClientes.setText("LISTA DE CLIENTES");
        jPanel1.add(lblTituloListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 520, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnListar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblApellMa;
    private javax.swing.JLabel lblApellPa;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblIconoCliente;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloListaClientes;
    private javax.swing.JLabel lblTítuloNewCliente;
    private javax.swing.JTable tblListaClientes;
    public javax.swing.JTextField txtApellMa;
    public javax.swing.JTextField txtApellPa;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
