/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.nk.views;

/**
 *
 * @author Pc
 */
public class VCompras extends javax.swing.JInternalFrame {

    /**
     * Creates new form VCompras
     */
    public VCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_IdUsuario = new javax.swing.JLabel();
        txt_IdUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_IdProveedor = new javax.swing.JLabel();
        txt_IdProveedor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblTítuloNewCompra = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTítulo2NewCompra = new javax.swing.JLabel();
        lbl_IdInsumo = new javax.swing.JLabel();
        txt_IdInsumo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnComprar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lbl_IconoCompra = new javax.swing.JLabel();
        btnVerInsumos = new javax.swing.JButton();
        btnVerCompras = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(54, 57, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(88, 101, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_IdUsuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lbl_IdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IdUsuario.setText("ID Usuario");
        jPanel2.add(lbl_IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        txt_IdUsuario.setBackground(new java.awt.Color(88, 101, 242));
        txt_IdUsuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_IdUsuario.setForeground(new java.awt.Color(250, 250, 250));
        txt_IdUsuario.setBorder(null);
        txt_IdUsuario.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txt_IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 10));

        lbl_IdProveedor.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lbl_IdProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IdProveedor.setText("ID Proveedor");
        jPanel2.add(lbl_IdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        txt_IdProveedor.setBackground(new java.awt.Color(88, 101, 242));
        txt_IdProveedor.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_IdProveedor.setForeground(new java.awt.Color(250, 250, 250));
        txt_IdProveedor.setBorder(null);
        txt_IdProveedor.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txt_IdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 190, 10));

        lblTítuloNewCompra.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewCompra.setText("ACTORES");
        jPanel2.add(lblTítuloNewCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(54, 57, 63));
        btnRegistrar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 440));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTítulo2NewCompra.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítulo2NewCompra.setText("NUEVO INSUMO");
        jPanel3.add(lblTítulo2NewCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        lbl_IdInsumo.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lbl_IdInsumo.setText("ID Insumo");
        jPanel3.add(lbl_IdInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        txt_IdInsumo.setBackground(new java.awt.Color(204, 204, 204));
        txt_IdInsumo.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_IdInsumo.setForeground(new java.awt.Color(250, 250, 250));
        txt_IdInsumo.setBorder(null);
        txt_IdInsumo.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel3.add(txt_IdInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 40));

        jSeparator3.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator3.setForeground(new java.awt.Color(54, 57, 63));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 10));

        lblCantidad.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblCantidad.setText("Cantidad");
        jPanel3.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        txtCantidad.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidad.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(250, 250, 250));
        txtCantidad.setBorder(null);
        txtCantidad.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 40));

        jSeparator4.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator4.setForeground(new java.awt.Color(54, 57, 63));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 10));

        lblPrecio.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblPrecio.setText("Precio");
        jPanel3.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        txtPrecio.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecio.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(250, 250, 250));
        txtPrecio.setBorder(null);
        txtPrecio.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 40));

        jSeparator5.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator5.setForeground(new java.awt.Color(54, 57, 63));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, 10));

        btnComprar.setBackground(new java.awt.Color(54, 57, 63));
        btnComprar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("Comprar");
        btnComprar.setBorder(null);
        btnComprar.setContentAreaFilled(false);
        btnComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprar.setFocusPainted(false);
        btnComprar.setFocusable(false);
        btnComprar.setOpaque(true);
        btnComprar.setRequestFocusEnabled(false);
        btnComprar.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 130, 50));

        btnAgregar.setBackground(new java.awt.Color(54, 57, 63));
        btnAgregar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setFocusPainted(false);
        btnAgregar.setFocusable(false);
        btnAgregar.setOpaque(true);
        btnAgregar.setRequestFocusEnabled(false);
        btnAgregar.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 130, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 420, 440));

        lbl_IconoCompra.setBackground(new java.awt.Color(88, 101, 242));
        lbl_IconoCompra.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IconoCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_IconoCompra.setText("(colocar icono Compra - editar luego)");
        jPanel1.add(lbl_IconoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 90, 80));

        btnVerInsumos.setBackground(new java.awt.Color(255, 255, 255));
        btnVerInsumos.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnVerInsumos.setForeground(new java.awt.Color(54, 57, 63));
        btnVerInsumos.setText("Ver insumos");
        btnVerInsumos.setBorder(null);
        btnVerInsumos.setContentAreaFilled(false);
        btnVerInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerInsumos.setFocusPainted(false);
        btnVerInsumos.setFocusable(false);
        btnVerInsumos.setOpaque(true);
        btnVerInsumos.setRequestFocusEnabled(false);
        btnVerInsumos.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(btnVerInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 130, 50));

        btnVerCompras.setBackground(new java.awt.Color(255, 255, 255));
        btnVerCompras.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnVerCompras.setForeground(new java.awt.Color(54, 57, 63));
        btnVerCompras.setText("Ver compras");
        btnVerCompras.setBorder(null);
        btnVerCompras.setContentAreaFilled(false);
        btnVerCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerCompras.setFocusPainted(false);
        btnVerCompras.setFocusable(false);
        btnVerCompras.setOpaque(true);
        btnVerCompras.setRequestFocusEnabled(false);
        btnVerCompras.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(btnVerCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnComprar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnVerCompras;
    public javax.swing.JButton btnVerInsumos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTítulo2NewCompra;
    private javax.swing.JLabel lblTítuloNewCompra;
    private javax.swing.JLabel lbl_IconoCompra;
    private javax.swing.JLabel lbl_IdInsumo;
    private javax.swing.JLabel lbl_IdProveedor;
    private javax.swing.JLabel lbl_IdUsuario;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txt_IdInsumo;
    public javax.swing.JTextField txt_IdProveedor;
    public javax.swing.JTextField txt_IdUsuario;
    // End of variables declaration//GEN-END:variables
}
