/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.nk.views;

/**
 *
 * @author Pc
 */
public class VFichaCompra extends javax.swing.JInternalFrame {

    /** Creates new form VFichaCompra */
    public VFichaCompra() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIconoFichaCompra = new javax.swing.JLabel();
        lblTítuloFichaCompra = new javax.swing.JLabel();
        lbl_IdCompra = new javax.swing.JLabel();
        txt_IdCompra = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_IdUsuario = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lbl_IdProveedor = new javax.swing.JLabel();
        txt_IdUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtEstado = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_IdProveedor = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCompras = new javax.swing.JTable();
        lblTítuloListaCompras = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(54, 57, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(88, 101, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoFichaCompra.setBackground(new java.awt.Color(88, 101, 242));
        lblIconoFichaCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblIconoFichaCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoFichaCompra.setText("(colocar icono Insumo - editar luego)");
        jPanel2.add(lblIconoFichaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 80));

        lblTítuloFichaCompra.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloFichaCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloFichaCompra.setText("COMPRA");
        jPanel2.add(lblTítuloFichaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 50));

        lbl_IdCompra.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lbl_IdCompra.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IdCompra.setText("ID compra");
        jPanel2.add(lbl_IdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txt_IdCompra.setBackground(new java.awt.Color(88, 101, 242));
        txt_IdCompra.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_IdCompra.setForeground(new java.awt.Color(250, 250, 250));
        txt_IdCompra.setBorder(null);
        txt_IdCompra.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txt_IdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 10));

        lbl_IdUsuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lbl_IdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IdUsuario.setText("ID usuario");
        jPanel2.add(lbl_IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lblEstado.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado");
        jPanel2.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        lbl_IdProveedor.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lbl_IdProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IdProveedor.setText("ID Proveedor");
        jPanel2.add(lbl_IdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        txt_IdUsuario.setBackground(new java.awt.Color(88, 101, 242));
        txt_IdUsuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_IdUsuario.setForeground(new java.awt.Color(250, 250, 250));
        txt_IdUsuario.setBorder(null);
        txt_IdUsuario.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txt_IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 10));

        txtEstado.setBackground(new java.awt.Color(88, 101, 242));
        txtEstado.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(250, 250, 250));
        txtEstado.setBorder(null);
        txtEstado.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 190, 40));

        jSeparator3.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator3.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 190, 10));

        txt_IdProveedor.setBackground(new java.awt.Color(88, 101, 242));
        txt_IdProveedor.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_IdProveedor.setForeground(new java.awt.Color(250, 250, 250));
        txt_IdProveedor.setBorder(null);
        txt_IdProveedor.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txt_IdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 200, 40));

        jSeparator4.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator4.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 200, 10));

        lblFecha.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha");
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        txtFecha.setBackground(new java.awt.Color(88, 101, 242));
        txtFecha.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(250, 250, 250));
        txtFecha.setBorder(null);
        txtFecha.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 200, 40));

        jSeparator6.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator6.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 200, 10));

        btnActualizar.setBackground(new java.awt.Color(54, 57, 63));
        btnActualizar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setFocusable(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setRequestFocusEnabled(false);
        btnActualizar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 130, 50));

        btnEliminar.setBackground(new java.awt.Color(54, 57, 63));
        btnEliminar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 130, 50));

        btnConsultar.setBackground(new java.awt.Color(54, 57, 63));
        btnConsultar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setFocusPainted(false);
        btnConsultar.setFocusable(false);
        btnConsultar.setOpaque(true);
        btnConsultar.setRequestFocusEnabled(false);
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 630));

        tblListaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaCompras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 700, 430));

        lblTítuloListaCompras.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloListaCompras.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloListaCompras.setText("LISTA DE COMPRAS");
        jPanel1.add(lblTítuloListaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIconoFichaCompra;
    private javax.swing.JLabel lblTítuloFichaCompra;
    private javax.swing.JLabel lblTítuloListaCompras;
    private javax.swing.JLabel lbl_IdCompra;
    private javax.swing.JLabel lbl_IdProveedor;
    private javax.swing.JLabel lbl_IdUsuario;
    public javax.swing.JTable tblListaCompras;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txt_IdCompra;
    public javax.swing.JTextField txt_IdProveedor;
    public javax.swing.JTextField txt_IdUsuario;
    // End of variables declaration//GEN-END:variables

}
