/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nk.views;

/**
 *
 * @author yanni
 */
public class VMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public VMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmHome = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        miLogin = new javax.swing.JMenuItem();
        jmOperaciones = new javax.swing.JMenu();
        jmiMovimientosInternos = new javax.swing.JMenuItem();
        jmiAbastecer = new javax.swing.JMenuItem();
        jmiVenta = new javax.swing.JMenuItem();
        jmiCliente = new javax.swing.JMenuItem();
        jmiProveedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopMenuLayout = new javax.swing.GroupLayout(desktopMenu);
        desktopMenu.setLayout(desktopMenuLayout);
        desktopMenuLayout.setHorizontalGroup(
            desktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopMenuLayout.setVerticalGroup(
            desktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jmHome.setText("Sesion");

        miLogout.setText("Logout");
        jmHome.add(miLogout);

        miLogin.setText("Login");
        jmHome.add(miLogin);

        jMenuBar1.add(jmHome);

        jmOperaciones.setText("Operaciones");

        jmiMovimientosInternos.setText("Movimientos Internos");
        jmiMovimientosInternos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMovimientosInternosActionPerformed(evt);
            }
        });
        jmOperaciones.add(jmiMovimientosInternos);

        jmiAbastecer.setText("Abastecer");
        jmOperaciones.add(jmiAbastecer);

        jmiVenta.setText("Venta");
        jmOperaciones.add(jmiVenta);

        jmiCliente.setText("Cliente");
        jmOperaciones.add(jmiCliente);

        jmiProveedor.setText("Proveedor");
        jmOperaciones.add(jmiProveedor);

        jMenuBar1.add(jmOperaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMovimientosInternosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMovimientosInternosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMovimientosInternosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktopMenu;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jmHome;
    public javax.swing.JMenu jmOperaciones;
    public javax.swing.JMenuItem jmiAbastecer;
    public javax.swing.JMenuItem jmiCliente;
    public javax.swing.JMenuItem jmiMovimientosInternos;
    public javax.swing.JMenuItem jmiProveedor;
    public javax.swing.JMenuItem jmiVenta;
    public javax.swing.JMenuItem miLogin;
    public javax.swing.JMenuItem miLogout;
    // End of variables declaration//GEN-END:variables
}
