/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nk.views;

/**
 *
 * @author Usuario
 */
public class VMovimientoI extends javax.swing.JInternalFrame {

    /**
     * Creates new form VMovimientoI
     */
    public VMovimientoI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblIconoProveedor = new javax.swing.JLabel();
        lblTítuloNewProveedor1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombreProductoMI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellPa = new javax.swing.JLabel();
        lblApellMa = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        txtPrecioMI = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtApellMa = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtDescripcionMI = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblTelefono1 = new javax.swing.JLabel();
        txtStockMI = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegistrarMI = new javax.swing.JButton();
        btnActualizarMI = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListarMI = new javax.swing.JButton();
        btnConsultarMI = new javax.swing.JButton();
        lblTítuloNewProveedor3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTítuloNewProveedor2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(54, 57, 63));

        jPanel2.setBackground(new java.awt.Color(88, 101, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoProveedor.setBackground(new java.awt.Color(88, 101, 242));
        lblIconoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblIconoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoProveedor.setText("(colocar icono proveedor- editar luego)");
        jPanel2.add(lblIconoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 80));

        lblTítuloNewProveedor1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewProveedor1.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewProveedor1.setText("INTERNOS");
        jPanel2.add(lblTítuloNewProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 50));

        lblNombres.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("Nombre Producto");
        jPanel2.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtNombreProductoMI.setBackground(new java.awt.Color(88, 101, 242));
        txtNombreProductoMI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtNombreProductoMI.setForeground(new java.awt.Color(250, 250, 250));
        txtNombreProductoMI.setBorder(null);
        txtNombreProductoMI.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtNombreProductoMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 10));

        lblApellPa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblApellPa.setForeground(new java.awt.Color(255, 255, 255));
        lblApellPa.setText("Precio");
        jPanel2.add(lblApellPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblApellMa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblApellMa.setForeground(new java.awt.Color(255, 255, 255));
        lblApellMa.setText("Estado");
        jPanel2.add(lblApellMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        lblDNI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI.setText("Descripcion");
        jPanel2.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        txtPrecioMI.setBackground(new java.awt.Color(88, 101, 242));
        txtPrecioMI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtPrecioMI.setForeground(new java.awt.Color(250, 250, 250));
        txtPrecioMI.setBorder(null);
        txtPrecioMI.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtPrecioMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 10));

        txtApellMa.setBackground(new java.awt.Color(88, 101, 242));
        txtApellMa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtApellMa.setForeground(new java.awt.Color(250, 250, 250));
        txtApellMa.setBorder(null);
        txtApellMa.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtApellMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 40));

        jSeparator3.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator3.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 10));

        txtDescripcionMI.setBackground(new java.awt.Color(88, 101, 242));
        txtDescripcionMI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtDescripcionMI.setForeground(new java.awt.Color(250, 250, 250));
        txtDescripcionMI.setBorder(null);
        txtDescripcionMI.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtDescripcionMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 40));

        jSeparator4.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator4.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 200, 10));

        lblTelefono1.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblTelefono1.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono1.setText("Stock");
        jPanel2.add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txtStockMI.setBackground(new java.awt.Color(88, 101, 242));
        txtStockMI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtStockMI.setForeground(new java.awt.Color(250, 250, 250));
        txtStockMI.setBorder(null);
        txtStockMI.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtStockMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, 40));

        jSeparator6.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator6.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 10));

        btnRegistrarMI.setBackground(new java.awt.Color(54, 57, 63));
        btnRegistrarMI.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrarMI.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarMI.setText("Registrar");
        btnRegistrarMI.setBorder(null);
        btnRegistrarMI.setContentAreaFilled(false);
        btnRegistrarMI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarMI.setFocusPainted(false);
        btnRegistrarMI.setFocusable(false);
        btnRegistrarMI.setOpaque(true);
        btnRegistrarMI.setRequestFocusEnabled(false);
        btnRegistrarMI.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrarMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 50));

        btnActualizarMI.setBackground(new java.awt.Color(54, 57, 63));
        btnActualizarMI.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnActualizarMI.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarMI.setText("Actualizar");
        btnActualizarMI.setBorder(null);
        btnActualizarMI.setContentAreaFilled(false);
        btnActualizarMI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarMI.setFocusPainted(false);
        btnActualizarMI.setFocusable(false);
        btnActualizarMI.setOpaque(true);
        btnActualizarMI.setRequestFocusEnabled(false);
        btnActualizarMI.setVerifyInputWhenFocusTarget(false);
        btnActualizarMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMIActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 130, 50));

        btnEliminar.setBackground(new java.awt.Color(54, 57, 63));
        btnEliminar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 50));

        btnListarMI.setBackground(new java.awt.Color(54, 57, 63));
        btnListarMI.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnListarMI.setForeground(new java.awt.Color(255, 255, 255));
        btnListarMI.setText("Listar");
        btnListarMI.setBorder(null);
        btnListarMI.setContentAreaFilled(false);
        btnListarMI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarMI.setFocusPainted(false);
        btnListarMI.setFocusable(false);
        btnListarMI.setOpaque(true);
        btnListarMI.setRequestFocusEnabled(false);
        btnListarMI.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnListarMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 50));

        btnConsultarMI.setBackground(new java.awt.Color(54, 57, 63));
        btnConsultarMI.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnConsultarMI.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarMI.setText("Consultar");
        btnConsultarMI.setBorder(null);
        btnConsultarMI.setContentAreaFilled(false);
        btnConsultarMI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarMI.setFocusPainted(false);
        btnConsultarMI.setFocusable(false);
        btnConsultarMI.setOpaque(true);
        btnConsultarMI.setRequestFocusEnabled(false);
        btnConsultarMI.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnConsultarMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 130, 50));

        lblTítuloNewProveedor3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewProveedor3.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewProveedor3.setText("MOVIMIENTOS");
        jPanel2.add(lblTítuloNewProveedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 290, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblTítuloNewProveedor2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewProveedor2.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewProveedor2.setText("LISTA DE PRODUCTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblTítuloNewProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lblTítuloNewProveedor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarMI;
    public javax.swing.JButton btnConsultarMI;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnListarMI;
    public javax.swing.JButton btnRegistrarMI;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellMa;
    private javax.swing.JLabel lblApellPa;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblIconoProveedor;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTítuloNewProveedor1;
    private javax.swing.JLabel lblTítuloNewProveedor2;
    private javax.swing.JLabel lblTítuloNewProveedor3;
    public javax.swing.JTextField txtApellMa;
    public javax.swing.JTextField txtDescripcionMI;
    public javax.swing.JTextField txtNombreProductoMI;
    public javax.swing.JTextField txtPrecioMI;
    public javax.swing.JTextField txtStockMI;
    // End of variables declaration//GEN-END:variables
}
