/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nk.views;

/**
 *
 * @author Usuario
 */
public class VMovimientoI extends javax.swing.JInternalFrame {

    /**
     * Creates new form VMovimientoI
     */
    public VMovimientoI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblIconoProveedor = new javax.swing.JLabel();
        lblTítuloNewProveedor1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellPa = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblTelefono1 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblTítuloNewProveedor3 = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtDescuento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaProductos = new javax.swing.JTable();
        lblTítuloNewProveedor2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(54, 57, 63));
        setClosable(true);

        jPanel2.setBackground(new java.awt.Color(88, 101, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoProveedor.setBackground(new java.awt.Color(88, 101, 242));
        lblIconoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblIconoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoProveedor.setText("(colocar icono proveedor- editar luego)");
        jPanel2.add(lblIconoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 80));

        lblTítuloNewProveedor1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewProveedor1.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewProveedor1.setText("INTERNOS");
        jPanel2.add(lblTítuloNewProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 50));

        lblNombres.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("Nombre");
        jPanel2.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtNombre.setBackground(new java.awt.Color(88, 101, 242));
        txtNombre.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(250, 250, 250));
        txtNombre.setBorder(null);
        txtNombre.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 10));

        lblApellPa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblApellPa.setForeground(new java.awt.Color(255, 255, 255));
        lblApellPa.setText("Precio");
        jPanel2.add(lblApellPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        lblDNI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI.setText("Descripcion");
        jPanel2.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(88, 101, 242));
        txtPrecio.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(250, 250, 250));
        txtPrecio.setBorder(null);
        txtPrecio.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 10));

        txtDescripcion.setBackground(new java.awt.Color(88, 101, 242));
        txtDescripcion.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(250, 250, 250));
        txtDescripcion.setBorder(null);
        txtDescripcion.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 40));

        jSeparator4.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator4.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 200, 10));

        lblTelefono1.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblTelefono1.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono1.setText("Stock");
        jPanel2.add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        txtStock.setBackground(new java.awt.Color(88, 101, 242));
        txtStock.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtStock.setForeground(new java.awt.Color(250, 250, 250));
        txtStock.setBorder(null);
        txtStock.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 40));

        jSeparator6.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator6.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 200, 10));

        btnRegistrar.setBackground(new java.awt.Color(54, 57, 63));
        btnRegistrar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 50));

        btnActualizar.setBackground(new java.awt.Color(54, 57, 63));
        btnActualizar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setFocusable(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setRequestFocusEnabled(false);
        btnActualizar.setVerifyInputWhenFocusTarget(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 130, 50));

        btnEliminar.setBackground(new java.awt.Color(54, 57, 63));
        btnEliminar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 50));

        btnListar.setBackground(new java.awt.Color(54, 57, 63));
        btnListar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.setBorder(null);
        btnListar.setContentAreaFilled(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.setFocusPainted(false);
        btnListar.setFocusable(false);
        btnListar.setOpaque(true);
        btnListar.setRequestFocusEnabled(false);
        btnListar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 50));

        btnConsultar.setBackground(new java.awt.Color(54, 57, 63));
        btnConsultar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setFocusPainted(false);
        btnConsultar.setFocusable(false);
        btnConsultar.setOpaque(true);
        btnConsultar.setRequestFocusEnabled(false);
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 130, 50));

        lblTítuloNewProveedor3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewProveedor3.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewProveedor3.setText("MOVIMIENTOS");
        jPanel2.add(lblTítuloNewProveedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 290, 50));

        lblDescuento.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblDescuento.setForeground(new java.awt.Color(255, 255, 255));
        lblDescuento.setText("Descuento");
        jPanel2.add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator7.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 10));

        txtDescuento.setBackground(new java.awt.Color(88, 101, 242));
        txtDescuento.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(250, 250, 250));
        txtDescuento.setBorder(null);
        txtDescuento.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, 40));

        tblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaProductos);

        lblTítuloNewProveedor2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewProveedor2.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewProveedor2.setText("LISTA DE PRODUCTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblTítuloNewProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTítuloNewProveedor2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnListar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblApellPa;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblIconoProveedor;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTítuloNewProveedor1;
    private javax.swing.JLabel lblTítuloNewProveedor2;
    private javax.swing.JLabel lblTítuloNewProveedor3;
    public javax.swing.JTable tblListaProductos;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtDescuento;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
