/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.nk.views;

/**
 *
 * @author Pc
 */
public class VProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VProveedor
     */
    public VProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIconoProveedor = new javax.swing.JLabel();
        lblTítuloNewProveedor1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellPa = new javax.swing.JLabel();
        lblApellMa = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtApellPa = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtApellMa = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtRUC = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblTelefono1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblTítuloListaProveedores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaProveedores = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(54, 57, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(88, 101, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoProveedor.setBackground(new java.awt.Color(88, 101, 242));
        lblIconoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblIconoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoProveedor.setText("(colocar icono proveedor- editar luego)");
        jPanel2.add(lblIconoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 80));

        lblTítuloNewProveedor1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewProveedor1.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewProveedor1.setText("NUEVO PROVEEDOR");
        jPanel2.add(lblTítuloNewProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 50));

        lblNombres.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("Nombres");
        jPanel2.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtNombres.setBackground(new java.awt.Color(88, 101, 242));
        txtNombres.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(250, 250, 250));
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 10));

        lblApellPa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblApellPa.setForeground(new java.awt.Color(255, 255, 255));
        lblApellPa.setText("Apellido Paterno");
        jPanel2.add(lblApellPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblApellMa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblApellMa.setForeground(new java.awt.Color(255, 255, 255));
        lblApellMa.setText("Apellido Materno");
        jPanel2.add(lblApellMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        lblDNI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI.setText("RUC");
        jPanel2.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Teléfono");
        jPanel2.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        txtApellPa.setBackground(new java.awt.Color(88, 101, 242));
        txtApellPa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtApellPa.setForeground(new java.awt.Color(250, 250, 250));
        txtApellPa.setBorder(null);
        txtApellPa.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtApellPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 10));

        txtApellMa.setBackground(new java.awt.Color(88, 101, 242));
        txtApellMa.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtApellMa.setForeground(new java.awt.Color(250, 250, 250));
        txtApellMa.setBorder(null);
        txtApellMa.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtApellMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 40));

        jSeparator3.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator3.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 10));

        txtRUC.setBackground(new java.awt.Color(88, 101, 242));
        txtRUC.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtRUC.setForeground(new java.awt.Color(250, 250, 250));
        txtRUC.setBorder(null);
        txtRUC.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 40));

        jSeparator4.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator4.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 200, 10));

        txtTelefono.setBackground(new java.awt.Color(88, 101, 242));
        txtTelefono.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(250, 250, 250));
        txtTelefono.setBorder(null);
        txtTelefono.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 200, 40));

        jSeparator5.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator5.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 200, 10));

        lblTelefono1.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblTelefono1.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono1.setText("DNI");
        jPanel2.add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txtDNI.setBackground(new java.awt.Color(88, 101, 242));
        txtDNI.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(250, 250, 250));
        txtDNI.setBorder(null);
        txtDNI.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, 40));

        jSeparator6.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator6.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 10));

        btnRegistrar.setBackground(new java.awt.Color(54, 57, 63));
        btnRegistrar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 50));

        btnActualizar.setBackground(new java.awt.Color(54, 57, 63));
        btnActualizar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setFocusable(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setRequestFocusEnabled(false);
        btnActualizar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 130, 50));

        btnEliminar.setBackground(new java.awt.Color(54, 57, 63));
        btnEliminar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 50));

        btnListar.setBackground(new java.awt.Color(54, 57, 63));
        btnListar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.setBorder(null);
        btnListar.setContentAreaFilled(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.setFocusPainted(false);
        btnListar.setFocusable(false);
        btnListar.setOpaque(true);
        btnListar.setRequestFocusEnabled(false);
        btnListar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 50));

        btnConsultar.setBackground(new java.awt.Color(54, 57, 63));
        btnConsultar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setFocusPainted(false);
        btnConsultar.setFocusable(false);
        btnConsultar.setOpaque(true);
        btnConsultar.setRequestFocusEnabled(false);
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 600));

        lblTítuloListaProveedores.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloListaProveedores.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloListaProveedores.setText("LISTA DE PROVEEDORES");
        jPanel1.add(lblTítuloListaProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        tblListaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaProveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 580, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnListar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblApellMa;
    private javax.swing.JLabel lblApellPa;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblIconoProveedor;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTítuloListaProveedores;
    private javax.swing.JLabel lblTítuloNewProveedor1;
    public javax.swing.JTable tblListaProveedores;
    public javax.swing.JTextField txtApellMa;
    public javax.swing.JTextField txtApellPa;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtRUC;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
