/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nk.views;

/**
 *
 * @author USUARIO
 */
public class VVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form VVentas
     */
    public VVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIconoVenta = new javax.swing.JLabel();
        lblTítuloNewVenta = new javax.swing.JLabel();
        lblId_usuario = new javax.swing.JLabel();
        txtId_usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblId_cliente = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtId_cliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblImpuesto = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaVentas = new javax.swing.JTable();
        lblTítuloListaVentas = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(54, 57, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(88, 101, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoVenta.setBackground(new java.awt.Color(88, 101, 242));
        lblIconoVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblIconoVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoVenta.setText("(colocar icono Venta - editar luego)");
        jPanel2.add(lblIconoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 80));

        lblTítuloNewVenta.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloNewVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewVenta.setText("NUEVA VENTA");
        jPanel2.add(lblTítuloNewVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 50));

        lblId_usuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblId_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lblId_usuario.setText("ID Usuario");
        jPanel2.add(lblId_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtId_usuario.setBackground(new java.awt.Color(88, 101, 242));
        txtId_usuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtId_usuario.setForeground(new java.awt.Color(250, 250, 250));
        txtId_usuario.setBorder(null);
        txtId_usuario.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtId_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 10));

        lblId_cliente.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblId_cliente.setForeground(new java.awt.Color(255, 255, 255));
        lblId_cliente.setText("ID Cliente");
        jPanel2.add(lblId_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblTotal.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        txtId_cliente.setBackground(new java.awt.Color(88, 101, 242));
        txtId_cliente.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtId_cliente.setForeground(new java.awt.Color(250, 250, 250));
        txtId_cliente.setBorder(null);
        txtId_cliente.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtId_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 10));

        txtTotal.setBackground(new java.awt.Color(88, 101, 242));
        txtTotal.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(250, 250, 250));
        txtTotal.setBorder(null);
        txtTotal.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 190, 40));

        jSeparator3.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator3.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 190, 10));

        lblImpuesto.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblImpuesto.setText("Impuesto");
        jPanel2.add(lblImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txtImpuesto.setBackground(new java.awt.Color(88, 101, 242));
        txtImpuesto.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtImpuesto.setForeground(new java.awt.Color(250, 250, 250));
        txtImpuesto.setBorder(null);
        txtImpuesto.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, 40));

        jSeparator6.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator6.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 10));

        btnRegistrar.setBackground(new java.awt.Color(54, 57, 63));
        btnRegistrar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 50));

        btnActualizar.setBackground(new java.awt.Color(54, 57, 63));
        btnActualizar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setFocusable(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setRequestFocusEnabled(false);
        btnActualizar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 130, 50));

        btnEliminar.setBackground(new java.awt.Color(54, 57, 63));
        btnEliminar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 50));

        btnListar.setBackground(new java.awt.Color(54, 57, 63));
        btnListar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.setBorder(null);
        btnListar.setContentAreaFilled(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.setFocusPainted(false);
        btnListar.setFocusable(false);
        btnListar.setOpaque(true);
        btnListar.setRequestFocusEnabled(false);
        btnListar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 50));

        btnConsultar.setBackground(new java.awt.Color(54, 57, 63));
        btnConsultar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setFocusPainted(false);
        btnConsultar.setFocusable(false);
        btnConsultar.setOpaque(true);
        btnConsultar.setRequestFocusEnabled(false);
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 730));

        tblListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 580, 430));

        lblTítuloListaVentas.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTítuloListaVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloListaVentas.setText("LISTA DE VENTAS");
        jPanel1.add(lblTítuloListaVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnListar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblIconoVenta;
    private javax.swing.JLabel lblId_cliente;
    private javax.swing.JLabel lblId_usuario;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTítuloListaVentas;
    private javax.swing.JLabel lblTítuloNewVenta;
    public javax.swing.JTable tblListaVentas;
    public javax.swing.JTextField txtId_cliente;
    public javax.swing.JTextField txtId_usuario;
    public javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
