/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nk.views;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USUARIO
 */
public class VVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form VVentas
     */
    public VVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblId_usuario = new javax.swing.JLabel();
        txtId_usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblId_cliente = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtId_cliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblImpuesto = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTítuloNewInsumo = new javax.swing.JLabel();
        lblIconoVenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaVentas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblTituloListaClientes = new javax.swing.JLabel();
        btnDes = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(54, 57, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(77, 90, 225));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId_usuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblId_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lblId_usuario.setText("ID Usuario");
        jPanel2.add(lblId_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtId_usuario.setBackground(new java.awt.Color(88, 101, 242));
        txtId_usuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtId_usuario.setForeground(new java.awt.Color(250, 250, 250));
        txtId_usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 101, 242), 7));
        txtId_usuario.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtId_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator1.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 10));

        lblId_cliente.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblId_cliente.setForeground(new java.awt.Color(255, 255, 255));
        lblId_cliente.setText("ID Cliente");
        jPanel2.add(lblId_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblTotal.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        txtId_cliente.setBackground(new java.awt.Color(88, 101, 242));
        txtId_cliente.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtId_cliente.setForeground(new java.awt.Color(250, 250, 250));
        txtId_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 101, 242), 7));
        txtId_cliente.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtId_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator2.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 10));

        txtTotal.setBackground(new java.awt.Color(88, 101, 242));
        txtTotal.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(250, 250, 250));
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 101, 242), 7));
        txtTotal.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 190, 40));

        jSeparator3.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator3.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 190, 10));

        lblImpuesto.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        lblImpuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblImpuesto.setText("Impuesto");
        jPanel2.add(lblImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txtImpuesto.setBackground(new java.awt.Color(88, 101, 242));
        txtImpuesto.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtImpuesto.setForeground(new java.awt.Color(250, 250, 250));
        txtImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 101, 242), 7));
        txtImpuesto.setCaretColor(new java.awt.Color(220, 95, 0));
        jPanel2.add(txtImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, 40));

        jSeparator6.setBackground(new java.awt.Color(54, 57, 63));
        jSeparator6.setForeground(new java.awt.Color(54, 57, 63));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 10));

        btnRegistrar.setBackground(new java.awt.Color(54, 57, 63));
        btnRegistrar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\CODIGO\\AppConfeccionariaZB\\src\\main\\java\\com\\nk\\img\\Registrar.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFocusable(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.setRequestFocusEnabled(false);
        btnRegistrar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, 70));

        btnActualizar.setBackground(new java.awt.Color(54, 57, 63));
        btnActualizar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\CODIGO\\AppConfeccionariaZB\\src\\main\\java\\com\\nk\\img\\Actualizar.png")); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.setFocusable(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setRequestFocusEnabled(false);
        btnActualizar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, 70));

        btnEliminar.setBackground(new java.awt.Color(54, 57, 63));
        btnEliminar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\CODIGO\\AppConfeccionariaZB\\src\\main\\java\\com\\nk\\img\\tacho.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setRequestFocusEnabled(false);
        btnEliminar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 140, 70));

        btnListar.setBackground(new java.awt.Color(54, 57, 63));
        btnListar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\CODIGO\\AppConfeccionariaZB\\src\\main\\java\\com\\nk\\img\\listar.png")); // NOI18N
        btnListar.setText("Listar");
        btnListar.setBorder(null);
        btnListar.setContentAreaFilled(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.setFocusPainted(false);
        btnListar.setFocusable(false);
        btnListar.setOpaque(true);
        btnListar.setRequestFocusEnabled(false);
        btnListar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 140, 70));

        btnConsultar.setBackground(new java.awt.Color(54, 57, 63));
        btnConsultar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\CODIGO\\AppConfeccionariaZB\\src\\main\\java\\com\\nk\\img\\Consultar.png")); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setFocusPainted(false);
        btnConsultar.setFocusable(false);
        btnConsultar.setOpaque(true);
        btnConsultar.setRequestFocusEnabled(false);
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, 70));

        jPanel3.setBackground(new java.awt.Color(26, 36, 140));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTítuloNewInsumo.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        lblTítuloNewInsumo.setForeground(new java.awt.Color(255, 255, 255));
        lblTítuloNewInsumo.setText("NUEVO VENTA");
        jPanel3.add(lblTítuloNewInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 50));

        lblIconoVenta.setBackground(new java.awt.Color(88, 101, 242));
        lblIconoVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblIconoVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoVenta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\CODIGO\\AppConfeccionariaZB\\src\\main\\java\\com\\nk\\img\\estante.png")); // NOI18N
        jPanel3.add(lblIconoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 80));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 730));

        tblListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 680, 410));

        jPanel4.setBackground(new java.awt.Color(32, 34, 37));

        lblTituloListaClientes.setFont(new java.awt.Font("Segoe UI Black", 1, 55)); // NOI18N
        lblTituloListaClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloListaClientes.setText("LISTA DE VENTAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(lblTituloListaClientes)
                .addGap(115, 115, 115))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloListaClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 740, 100));

        btnDes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\CODIGO\\AppConfeccionariaZB\\src\\main\\java\\com\\nk\\img\\descargar.png")); // NOI18N
        btnDes.setText("Descargar");
        btnDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesActionPerformed
        try {
            tblListaVentas.print();
        } catch (PrinterException ex) {
            Logger.getLogger(VVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDes;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnListar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblIconoVenta;
    private javax.swing.JLabel lblId_cliente;
    private javax.swing.JLabel lblId_usuario;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblTituloListaClientes;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTítuloNewInsumo;
    public javax.swing.JTable tblListaVentas;
    public javax.swing.JTextField txtId_cliente;
    public javax.swing.JTextField txtId_usuario;
    public javax.swing.JTextField txtImpuesto;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
